---
title: My first GitHub Site
date: 2020-02-09
---
author: JerryZhang0920
email: jJinxuan0920@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My amazing first github pages

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
